version : '3.1'
services: 
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
        - 27017:27017
    volumes:
    - /data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    image: mchehab/app:latest
    command: mvn clean app:run
    links: 
      - mongodb
    expose:
      - 80  
    ports:
      - 80:80
    depends_on: 
      - mongodb